version: '2'
services:
  db:
    image: mysql:5.7
    volumes:
      - "./mysql-data:/var/lib/mysql"
      - "./db-init:/docker-entrypoint-initdb.d"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=drinkingisyes
      - MYSQL_DATABASE=ontap
  web:
    build: .
    volumes:
      - ".:/OnTap"
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=ontap
      - DB_USER=root
      - DB_PASSWORD=drinkingisyes
    depends_on:
      - db
